name: insta_assets_crop_example
description: Demonstrates how to use the insta_assets_crop plugin.

version: 0.0.1+2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  insta_assets_crop:
    path: ../

flutter:
  uses-material-design: true
